// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-zRb0PLktCZuPxvTq9w9SUiAJOeMAxw',
    appId: '1:992179001017:web:9363009e0aa2f3f8d26d68',
    messagingSenderId: '992179001017',
    projectId: 'my-instagram-clone-vand',
    authDomain: 'my-instagram-clone-vand.firebaseapp.com',
    storageBucket: 'my-instagram-clone-vand.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeL32fUWv2mF4Sp36MjQlT33ge12uPAL4',
    appId: '1:992179001017:android:2ad939fdf854ee4cd26d68',
    messagingSenderId: '992179001017',
    projectId: 'my-instagram-clone-vand',
    storageBucket: 'my-instagram-clone-vand.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsraTstn6iAQFf7ckaZJiqrgYJLNUZOY0',
    appId: '1:992179001017:ios:2e8b9aade9381a93d26d68',
    messagingSenderId: '992179001017',
    projectId: 'my-instagram-clone-vand',
    storageBucket: 'my-instagram-clone-vand.appspot.com',
    iosClientId: '992179001017-51iu9gnlfo73bjol15j35eoo75pp0qm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
